### ISSUE TITLE
Getting error message that Pleasant3D cannot open Standard Tesselated Geometry File Format

### ISSUE THREAD

**Issue by jamesarm97** [zaggo/Pleasant3D#21]
All of a sudden (I thought I had run it recently since updating) I cannot use Pleasant3D to open STL files. I get a message that it cannot open STL files (not a message that it cannot open a particular file). I tried compiling with the latest version of Xcode and running the precompiled version 2.6.1 (14) and they all do the same thing. Not sure what is going on. I sure hope there is a fix because I use it all the time to preview STL files. On El Capitan OSX

![screenshot 2015-09-28 15 28 09](https://cloud.githubusercontent.com/assets/929192/10146223/a630aeb0-65f5-11e5-8a5a-835480d65635.png)

**Comment by TheCase** [comment]
+1 

same message.

May have something to do with Gatekeeper and signed apps.  I noticed a lot of this in the system logs when I try to open STLs:
```
9/30/15 11:17:36.848 AM CoreServicesUIAgent[40690]: Error -60005 creating authorization
```

**Comment by zaggo** [comment]
This is a known issue. Somehow Apple managed to mess up STL file handling with Pleasant3D in the Mac OS X 10.10.5 update (and Mac OS 10.11). I'm still not sure what exactly is happening here...

I'm currently trying to track down the exact source of this issue.

**Comment by DaveCasey** [comment]
Yes, I am seeing the same thing with 10.10.5.
Interesting spelling of "Tesselated" autocorrect seems to prefer "Tessellated".

Pleasant3D is a key step in my 3D printing workflow.  If there is anything I can do to help narrow this down, please let me know.

**Comment by jamesarm97** [comment]
What I found interesting is when I tried to open a STL file initially it opened in XCode and actually was able to view it. I selected pleasant3d as the default app after that and that is when i noticed the problem. The quick look part seems to still work (if that is a function of pleasant3d)

--
James Armstrong

**Comment by zaggo** [comment]
It seems, that Apple decided to somehow add STL file support to the OS. On my system (OS X 10.11 (15A284) now STL QuickLook started to work again. However, now a QuickLook generator from Apple seems to generate the previews (and I don't like the images it generates that much although, the Apple QuickLook supports turning the previewed part live (just drag the preview with the mouse), which is pretty cool and definitely a new QuickLook feature):

`qlmanage -x -p <PathTo>/Hohlrad.stl` now generates this:
![bildschirmfoto 2015-10-17 um 11 05 59](https://cloud.githubusercontent.com/assets/154959/10557944/31982442-74bf-11e5-88b1-943280ce3b65.png)

However forcing Pleasant3D's QuickLook generator (`qlmanage -x -p <PathTo>/Hohlrad.stl -g /Applications/Pleasant3D.app/Contents/Library/QuickLook/STLQuickLook.qlgenerator -c com.pleasantsoftware.uti.stl`) shows the "old" QuickLook image:
![bildschirmfoto 2015-10-17 um 11 05 09](https://cloud.githubusercontent.com/assets/154959/10557951/58737990-74bf-11e5-9c9f-4a26b2f09bd1.png)

**Comment by zaggo** [comment]
And the QL Generator from Apple which is doing this seems to be `/System/Library/QuickLook/SceneKit.qlgenerator` which is recognizing the (until 10.10.5 not defined) UTI `public.standard-tesselated-geometry-format`
Since Pleasant3D uses the self defined UTI `com.pleasantsoftware.uti.stl` for STL files, I guess the System now has a problem to handle the two UTIs for the same file type.

The solution to this problem should be to add `public.standard-tesselated-geometry-format' to Pleasant3Ds UTI definition of STL documents.
I let you know how it goes...

**Comment by zaggo** [comment]
Yep, got it...

I'm currently fixing some "deprecated API" issues with the 10.11 SDK and Xcode 7, but I'll then push the working UTI configuration to GitHub.

I try to release an app update as soon as possible.

**Comment by zaggo** [comment]
Version 2.6.3 is now available (http://download.pleasantsoftware.com/pleasant3d/pleasant3d.zip). The changed sources are pushed into the repository.

Cheers!

**Comment by TheCase** [comment]
Thanks!

**Comment by jamesarm97** [comment]
Thank you. Although apple added STL quick look support I didn’t care for the look of it (too dark and hard to see). I also had noticed when I first filed the report that Xcode also loads STL files and lets you view them in Xcode so I knew something was up. Maybe they are gearing up to some 3d printer support in the future. Seems like I had read something about CUPS and 3d printer support coming. I think this is what I read: http://3dprint.com/86220/apple-cups-3d-printer-support/
